### ISSUE TITLE
Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by andris155** [SickSkillz/SLB-Tracker#11]
**Describe the bug**

**To Reproduce**
I don't know.

**Expected behavior**
No write fatal alert

**Screenshots**

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java version: Java 11
 - Minecraft version: 1.13.2

**Plugin (please complete the following information):**
 - Version: 2.13.5
 - Changed config: yes
 - Added or removed custom surprises: yes

**Additional notes**
```
[09:51:13] [Craft Scheduler Thread - 823/WARN]: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at org.sickskillz.superluckyblock.q.a(BlockUtils.java:43)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[09:51:13] [Craft Scheduler Thread - 823/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by SickSkillz** [comment]
Hmm, looks like the error is still there. I will look into it again.

**Comment by SickSkillz** [comment]
Related to #8.

**Comment by SickSkillz** [comment]
Might have been something server sided. Have changed something in the hopes it works, but I can't test it. Could you see if it is fixed?

**Comment by andris155** [comment]
2.15.1 not fixed this.

**Comment by andris155** [comment]
Latest versions fixed this.
