### ISSUE TITLE
Not compatible with new PlotSquared

### ISSUE THREAD

**Issue by andris155** [SickSkillz/SLB-Tracker#13]
**Describe the bug**
Not compatible new PlotSquared

**To Reproduce**
1. Install new PlotSquared.
2. Use Lucky Blocks on plots.

**Expected behavior**
This plugin works perfectly with new PlotSquared

**Screenshots**

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - Java version: 11
 - Minecraft version: 1.13.2

**Plugin (please complete the following information):**
 - Version: 2.15.1
 - Changed config: yes
 - Added or removed custom surprises: yes

**Additional notes**
```
[12:59:31] [Server thread/ERROR]: Could not pass event BlockBreakEvent to SuperLuckyBlock-Pro v2.15.1
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/object/Location
	at org.sickskillz.superluckyblock.ja.e(BlockBreakListener.java:76) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor473.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:226) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1290) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-492]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-492]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.object.Location
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-492]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 20 more
[12:59:37] [Server thread/ERROR]: Could not pass event BlockBreakEvent to SuperLuckyBlock-Pro v2.15.1
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/object/Location
	at org.sickskillz.superluckyblock.ja.e(BlockBreakListener.java:76) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor473.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:226) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1290) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-492]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-492]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:59:42] [Server thread/ERROR]: Could not pass event BlockBreakEvent to SuperLuckyBlock-Pro v2.15.1
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/object/Location
	at org.sickskillz.superluckyblock.ja.e(BlockBreakListener.java:76) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor473.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:226) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1290) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-492]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-492]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-492]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by SickSkillz** [comment]
I am aware of this issue, but I am not sure on how to solve it yet. I will add a check to prevent this error from happening on 1.13.

**Comment by andris155** [comment]
Please fix this, because Lucky Blocks destroy plot roads.

**Comment by SickSkillz** [comment]
I'm trying to come up with a way to do this. Will try to fix as fast as possible.
