### ISSUE TITLE
Error occurred while enabling SuperLuckyBlock v3.3.9, 3.4.0

### ISSUE THREAD

**Issue by andris155** [SickSkillz/SLB-Tracker#19]
**Describe the bug**

**To Reproduce**
1. Start server with SuperLuckyBlock plugin.

**Expected behavior**
SuperLuckyBlock works perfectly

**Screenshots or video**
If applicable, add screenshots or a video to help explain your problem.

**Server (please complete the following information):**
 - Java version: 11.0.5
 - Minecraft version: 1.14.4

**Plugin:**
 - Version: 3.3.9
 - Are you using the default config: no
 - Did you remove or add custom surprises: yes

**Debug Report:**
Please run the command /slb debug. This command will give you a link in the chat. 
Remove this line and the text under Debug Report and paste the link it gave you. 
`Cannot execute command 'slb' in plugin SuperLuckyBlock v3.3.9 - plugin is disabled.`

**Additional notes**
```
[15:06:56 INFO]: [SuperLuckyBlock] Enabling SuperLuckyBlock v3.3.9
[15:06:56 INFO]: -----------------------------------------------------------------------------------
[15:06:56 INFO]: _____ _ _ ____ _ _
[15:06:56 INFO]: / ____| | | | | | _ \| | | |
[15:06:56 INFO]: | (___ _ _ _ __ ___ _ __| | _ _ ___| | ___ _| |_) | | ___ ___| | __
[15:06:56 INFO]: \___ \| | | | '_ \ / _ \ '__| | | | | |/ __| |/ / | | | _ <| |/ _ \ / __| |/ /
[15:06:56 INFO]: ____) | |_| | |_) | __/ | | |___| |_| | (__| <| |_| | |_) | | (_) | (__| <
[15:06:56 INFO]: |_____/ \__,_| .__/ \___|_| |______\__,_|\___|_|\_\\__, |____/|_|\___/ \___|_|\_\
[15:06:56 INFO]: | | __/ |
[15:06:56 INFO]: |_| |___/
[15:06:56 INFO]: -----------------------------------------------------------------------------------
[15:06:56 INFO]: SLB >> Verifying and loading dependencies...
[15:06:56 ERROR]: Error occurred while enabling SuperLuckyBlock v3.3.9 (Is it up to date?)
java.lang.NoClassDefFoundError: io/sentry/event/interfaces/SentryInterface
at org.sickskillz.superluckyblock.cOm2.onEnable(SuperLuckyBlock.java:150) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-230]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-230]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-230]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: io.sentry.event.interfaces.SentryInterface
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-230]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-230]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
... 16 more
[15:06:56 INFO]: [SuperLuckyBlock] Disabling SuperLuckyBlock v3.3.9
```

`Plugins (94): AdditionsAPI, AdminVedelem, AdvancedAchievements, antiRedstoneClock, AnvilRestrict, ArmorStandEditor, BentoBox, Brewery, BuntetesLogolo, ChangeSkin, ChatControl, ChatReaction, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, ChristmasCalendar*, Citizens, CitizensCMD, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CustomCrafting, CustomOreGen, Duels, EnderContainers, EntityDetection, Ercgenerator, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, HeadDatabase*, HolographicDisplays, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv, PickupSpawners, PlaceholderAPI, PlugMan, PocketGames, PomaAdditions, ProtocolLib, RedstoneClockDetector, RestrictedCreative, ShopGUIPlus, Shopkeepers, SignEdit*, Sleepy*, StaffChat, StaffTime, Stats, SuperLuckyBlock, Szilveszter, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, VanillaAdditions, Vault, VillagerOptimiser, Votifier, VotingPlugin, WDLCompanion*, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge`

**Comment by SickSkillz** [comment]
Hello,
Please see if the lib folder exists in the SuperLuckyBlock folder. If it does, please remove all of the files inside it and try to restart your server and see if any errors appear. If the folder does not exist, please comment on this report.

**Comment by andris155** [comment]
<img width="672" alt="Annotation 2019-12-04 195035" src="https://user-images.githubusercontent.com/8324198/70171620-606cb600-16cf-11ea-8a53-448edcbc3f19.png">
Not work. Maybe not compatible with Java 11?

**Comment by andris155** [comment]
The old version write this.
```
[21:07:31 INFO]: [SuperLuckyBlock] Enabling SuperLuckyBlock v3.3.7
[21:07:31 INFO]: -----------------------------------------------------------------------------------
[21:07:31 INFO]:    _____                       _                _          ____  _            _
[21:07:31 INFO]:   / ____|                     | |              | |        |  _ \| |          | |
[21:07:31 INFO]:  | (___  _   _ _ __   ___ _ __| |    _   _  ___| | ___   _| |_) | | ___   ___| | __
[21:07:31 INFO]:   \___ \| | | | '_ \ / _ \ '__| |   | | | |/ __| |/ / | | |  _ <| |/ _ \ / __| |/ /
[21:07:31 INFO]:   ____) | |_| | |_) |  __/ |  | |___| |_| | (__|   <| |_| | |_) | | (_) | (__|   <
[21:07:31 INFO]:  |_____/ \__,_| .__/ \___|_|  |______\__,_|\___|_|\_\\__, |____/|_|\___/ \___|_|\_\
[21:07:31 INFO]:               | |                                     __/ |
[21:07:31 INFO]:               |_|                                    |___/
[21:07:31 INFO]: -----------------------------------------------------------------------------------
[21:07:31 INFO]: SLB >> Initializing Sentry...
[21:07:31 INFO]: SLB >> Loading and checking configs...
[21:07:31 INFO]: SLB >> Registering events...
[21:07:31 INFO]: -----------------------------------------------------------------------------------
[21:07:31 INFO]:    _____                       _                _          ____  _            _
[21:07:31 INFO]:   / ____|                     | |              | |        |  _ \| |          | |
[21:07:31 INFO]:  | (___  _   _ _ __   ___ _ __| |    _   _  ___| | ___   _| |_) | | ___   ___| | __
[21:07:31 INFO]:   \___ \| | | | '_ \ / _ \ '__| |   | | | |/ __| |/ / | | |  _ <| |/ _ \ / __| |/ /
[21:07:31 INFO]:   ____) | |_| | |_) |  __/ |  | |___| |_| | (__|   <| |_| | |_) | | (_) | (__|   <
[21:07:31 INFO]:  |_____/ \__,_| .__/ \___|_|  |______\__,_|\___|_|\_\\__, |____/|_|\___/ \___|_|\_\
[21:07:31 INFO]:               | |                                     __/ |
[21:07:31 INFO]:               |_|                                    |___/
[21:07:31 INFO]: -----------------------------------------------------------------------------------
[21:07:31 INFO]: SuperLuckyBlock caught an exception and reported it to Sentry.
[21:07:31 INFO]: Some parts of the plugin might not function correctly.
[21:07:31 INFO]: If this appears to be the case, please contact SickSkillz on SpigotMC or on Discord.
[21:07:31 INFO]: If this is a bug and it got reported to Sentry correctly, it should be fixed soon.
[21:07:31 INFO]:
[21:07:31 INFO]: Plugin Version: 3.3.7
[21:07:31 INFO]: Update Available: false
[21:07:31 INFO]:
[21:07:31 INFO]: Exception Message: Unable to find handler list for event org.bukkit.event.block.BlockEvent. Static getHandlerList method required!
[21:07:31 INFO]:
[21:07:31 INFO]: Full Stacktrace:
[21:07:31 INFO]: org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.block.BlockEvent. Static getHandlerList method required!
[21:07:31 INFO]:        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:641)
[21:07:31 INFO]:        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:639)
[21:07:31 INFO]:        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:578)
[21:07:31 INFO]:        at org.sickskillz.superluckyblock.bd.onEnable(SuperLuckyBlock.java:67)
[21:07:31 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:07:31 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[21:07:31 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[21:07:31 INFO]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[21:07:31 INFO]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[21:07:31 INFO]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[21:07:31 INFO]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[21:07:31 INFO]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[21:07:31 INFO]:        at java.base/java.lang.Thread.run(Thread.java:834)
[21:07:31 INFO]: -----------------------------------------------------------------------------------
[21:07:31 INFO]: SLB >> Startup aborted! Exception caught on startup. Please contact SickSkillz. Disabling plugin...
```

**Comment by andris155** [comment]
3.3.5 works perfectly
```
[21:11:08 INFO]: [SuperLuckyBlock] Enabling SuperLuckyBlock v3.3.5
[21:11:09 INFO]: -----------------------------------------------------------------------------------
[21:11:09 INFO]:    _____                       _                _          ____  _            _
[21:11:09 INFO]:   / ____|                     | |              | |        |  _ \| |          | |
[21:11:09 INFO]:  | (___  _   _ _ __   ___ _ __| |    _   _  ___| | ___   _| |_) | | ___   ___| | __
[21:11:09 INFO]:   \___ \| | | | '_ \ / _ \ '__| |   | | | |/ __| |/ / | | |  _ <| |/ _ \ / __| |/ /
[21:11:09 INFO]:   ____) | |_| | |_) |  __/ |  | |___| |_| | (__|   <| |_| | |_) | | (_) | (__|   <
[21:11:09 INFO]:  |_____/ \__,_| .__/ \___|_|  |______\__,_|\___|_|\_\\__, |____/|_|\___/ \___|_|\_\
[21:11:09 INFO]:               | |                                     __/ |
[21:11:09 INFO]:               |_|                                    |___/
[21:11:09 INFO]: -----------------------------------------------------------------------------------
[21:11:09 INFO]: SLB >> Initializing Sentry...
[21:11:09 INFO]: SLB >> Loading and checking configs...
[21:11:09 INFO]: SLB >> Registering events...
[21:11:09 INFO]: SLB >> Initializing custom luckyblocks...
[21:11:10 INFO]: SLB >> Registering wands...
[21:11:10 INFO]: SLB >> Initializing LuckyActions...
[21:11:10 INFO]: SLB >> Registering command...
[21:11:10 INFO]: SLB >> Creating tasks...
[21:11:10 INFO]: SLB >> Vault found! Hooking into it...
[21:11:10 INFO]: SLB >> SuperLuckyBlock has been enabled! (852ms)
```

**Comment by SickSkillz** [comment]
Could you show me a screenshot of your lib folder?

**Comment by andris155** [comment]
![Screenshot_20191208-152140](https://user-images.githubusercontent.com/8324198/70390783-85fb0780-19ce-11ea-957e-7290979f3b35.png)

**Comment by baticag** [comment]
I have the same issue

**Comment by baticag** [comment]
Still not working https://hastebin.com/huwojexofi.md

**Comment by SickSkillz** [comment]
Sorry I forgot to reply to the new comments. Reply I just posted on spigot regarding this: 
"I am aware of this issue, will look into it once I have some more time. It has something to do with Java 11 and loading dependencies. Version 3.3.7 should work so please use that one in the meantime: https://www.spigotmc.org/resources/superluckyblock-1-8-1-15-the-luckyblock-plugin-that-gives-you-full-control.48837/download?version=302383 "

**Comment by SickSkillz** [comment]
Should be fixed in the most recent update: https://www.spigotmc.org/resources/superluckyblock-1-8-1-15-the-luckyblock-plugin-that-gives-you-full-control.48837/
